name: my_photos
description: Demo of an application using Bloc to manage the camera.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  equatable: ^1.1.1
  path_provider: ^1.6.16
  path: ^1.6.4

  # Bloc: https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^6.0.5
  # Camera plugin: https://pub.dev/packages/camera
  camera: ^0.5.8+7
  # SQL database
  sqflite: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
  bloc_test: ^7.0.4

flutter:
  uses-material-design: true